emmalanguage/emma

emma-common/src/main/scala/eu/stratosphere/emma/api/DataBag.scala

This is a temporary workaround for avoiding the `collect` call when `vals` is not used. `ParallelizedDataBag` now initializes the collection to null, and only calls `collect` if `vals` is called, or the `ParallelizedDataBag` is being serialized.
Note, that the long-term solution will be to use broadcast variables.

[RUNTIME] Make the vals in ParallelizedDataBag lazily collected

---

emma-language/src/main/scala/eu/stratosphere/emma/compiler/lang/core/Core.scala
emma-language/src/main/scala/eu/stratosphere/emma/compiler/lang/core/DCE.scala
emma-language/src/test/scala/eu/stratosphere/emma/compiler/lang/core/DCESpec.scala

A note about side effects: DCE will remove any purely side-effecting method calls like `println`, because their return values are never used. To prevent this, we would need to wrap such calls in some kind of `effectful[T](eff: T): T` that is bypassed in transformations like ANF, DCE and CSE.

[IR] Reworked DCE based on compiler.ast

---

emma-common-macros/src/main/scala/eu/stratosphere/emma/ast/Trees.scala
emma-language/src/main/scala/eu/stratosphere/emma/compiler/Common.scala
emma-language/src/main/scala/eu/stratosphere/emma/compiler/Compiler.scala
emma-language/src/main/scala/eu/stratosphere/emma/compiler/lang/backend/Backend.scala
emma-language/src/main/scala/eu/stratosphere/emma/compiler/lang/backend/Order.scala
emma-language/src/test/scala/eu/stratosphere/emma/compiler/lang/comprehension/CombinationSpec.scala
emma-language/src/test/scala/eu/stratosphere/emma/compiler/lang/core/OrderSpec.scala

When translating to Flink or Spark, we have to know for every piece of code whether it will be executed in the driver, or in a higher-order context (UDF). This PR adds the `Order` trait to `core`, which makes this decision, and disambiguates when necessary (that is, duplicates code that might get called both from the driver and from UDFs).
Unfortunately it has some false positives, i.e. it says that some code is high, when in fact it will only be  executed in the driver, but I don't think it's worth it to spend more time now on this, because making this perfect would be very hard.

[IR] Added order disambiguation.

---

.travis.yml

This also adds `emma-language` to one of the `-PIT` tests, so that
the spec pipelines are checked whether the results compile (see `compile-spec-pipelines`).

[INFRA] Fixed config of Travis build.

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/ScalaTraversable.scala
emma-language/src/main/scala/org/emmalanguage/api/package.scala
emma-language/src/test/scala/org/emmalanguage/api/DataBagSpec.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala

This basically inlines the `FoldMacros` from the old API directly within the `DataBag` API.
I think that it might be beneficial to hold on to the combinator form for a while and not bluntly substitute before entering the compiler pipeline.
In addition, the proposed changes allow for resolving various FIXME comments in the "structural recursion" spec.

[API] Made specific folds an explicit part of the new `DataBag` API.

---

emma-language/src/main/scala/org/emmalanguage/ast/AST.scala
emma-language/src/main/scala/org/emmalanguage/ast/CommonAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Methods.scala
emma-language/src/main/scala/org/emmalanguage/ast/Symbols.scala
emma-language/src/main/scala/org/emmalanguage/ast/Transversers.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Comprehension.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/ANF.scala
emma-language/src/main/scala/org/emmalanguage/util/Functions.scala

- Added pre-pass to remove `TypeTree.original`s from the source tree;
- Added more function utils;
- Changed `Comprehension`s to work with unqualified refs;
- Added some type extractors;
- Improved handling of implicit/var-args in method calls.

[IR] Minor additions to the new IR

---

emma-language/src/main/scala/org/emmalanguage/ast/AST.scala
emma-language/src/main/scala/org/emmalanguage/ast/CommonAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Methods.scala
emma-language/src/main/scala/org/emmalanguage/ast/Symbols.scala
emma-language/src/main/scala/org/emmalanguage/ast/Terms.scala
emma-language/src/main/scala/org/emmalanguage/ast/Trees.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/LanguageSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/source/Foreach2LoopSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/source/LanguageSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/source/PatternMatchingSpec.scala

It turned out that replacing symbols and changing the owner are related operations with similar implementation, therefore I fused them in `Sym.subst`. `Tree.rename` and `Owner.at` just forward to it. Hopefully, this will solve our issues related to method symbols and (type) parameters.
fixes #255

[IR] Fixed `Tree.rename` and `Owner.at` via `Sym.subst`

---

emma-language/src/main/scala/org/emmalanguage/ast/CommonAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/JavaAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/MacroAST.scala

Also, print the tree when `JavaAST.compile` or `JavaAST.typeCheck` fails.
Also, add a workaround for https://issues.scala-lang.org/browse/SI-9932 in `JavaAST.compile`.

[IR] Modify CommonAST.eval to not fail for typechecked trees.

---

emma-language/src/main/scala/org/emmalanguage/ast/AST.scala
emma-language/src/main/scala/org/emmalanguage/ast/JavaAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Loops.scala
emma-language/src/main/scala/org/emmalanguage/ast/MacroAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Terms.scala
emma-language/src/main/scala/org/emmalanguage/ast/Trees.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DSCF.scala

Also, removed etaCompact, etaExpand, TermName.Eta, TermName.While, TermName.DoWhile.
Fixes #265.

[IR] Added different suffix to fresh names between MacroAST and JavaAST.

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/package.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/source/Source.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala

So far, for every resolution of `Meta`, the compiler created the following code:
```
(`package`.this.Meta.apply(
`package`.ctagFor(
`package`.this.Meta.apply(
Predef.this.implicitly,
`package`.ttagFor(
`package`.this.Meta.apply(
Predef.this.implicitly,
Predef.this.implicitly
)
)
)
),
`package`.ttagFor(
`package`.this.Meta.apply(
`package`.ctagFor(
`package`.this.Meta.apply(
Predef.this.implicitly,
Predef.this.implicitly
)
),
Predef.this.implicitly
)
)
))
```
Now it looks like this, as it should be:
```
`package`.this.Meta.apply(Predef.this.implicitly, Predef.this.implicitly)
```
This makes compilation faster. For example, `BaseCodegenTest` compiles almost twice as fast.
Additionally, I moved `removeImplicits` to the very beginning of the pipeline to get rid of the very large trees that …

[API] Refactored the Meta implicits to have shorter resolutions.

---

emma-language/src/main/scala/org/emmalanguage/ast/AST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Trampoline.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/TrampolineSpec.scala

Tail calls in the mutually recursive methods introduced by DSCF are
wrapped in a trampoline provided by `scala.util.control.TailCalls`.
This makes the resulting code stack-safe.

[IR] Added a Trampoline.transform to Core.lower

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-flink/src/test/scala/org/emmalanguage/compiler/flink/dataset/CodegenSpec.scala
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/package.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/Order.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/TranslateToDataflows.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Combination.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Normalize.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DCE.scala
emma-language/src/test/scala/org/emmalanguage/compiler/BaseCodegenSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/BaseCompilerSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala
emma-spark/src/test/scala/org/emmalanguage/compiler/spark/rdd/CodegenSpec.scala

The main thing here is the first commit, which takes care of `equiJoin` and `cross`, and changes `BaseCodegenTest` to use comprehension combination instead of just desugaring.

[IR] Handle equiJoin and cross

---

NOTICE
emma-gui/public/cytoscape-template.html
emma-gui/src/main/scala/org/emmalanguage/server/GraphServlet.scala
emma-gui/src/main/scala/org/emmalanguage/server/HttpServer.scala
emma-language/pom.xml
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/tools/GraphTools.scala
pom.xml

Creates visual graphs using `ControlFlow.cfg` and  http://js.cytoscape.org/ and renders them in a browser for analysis. Very early stage, but maybe useful nevertheless.
- `emma-language`
+ `compiler.tools.GraphTools.renderGraph` -- `Tree => Tree` to be inserted into compiler pipelines (example see below). (Currently) Renders the data dependency graph as an effect to a `JSON` file to be consumed by `GraphServlet`
- `emma-gui`
+ `HttpServer` -- Receives the location of JSON-Graphs as the first program argument (e.g. `/tmp/emma/graphs/`)
+ `GraphServlet` -- exposes `/graph/`, renders a HTML website that  renders the graphs using.
(assuming `compiler.GraphTools` is in scope)
```scala
/*private */ val renderToTemp = GraphTools.renderGraph(java.nio.file.Paths.get("/tmp/emma/graphs")) _ …
```

[GUI] Prototype GraphTools and Graph Webapp /w Cytoscape

---

emma-examples/src/main/scala/org/emmalanguage/examples/graphs/EnumerateTriangles.scala
emma-examples/src/main/scala/org/emmalanguage/examples/graphs/TransitiveClosure.scala
emma-examples/src/main/scala/org/emmalanguage/examples/graphs/model.scala
emma-examples/src/main/scala/org/emmalanguage/examples/imdb/GraphPreprocessing.scala
emma-examples/src/main/scala/org/emmalanguage/examples/ml/model.scala
emma-language/src/main/scala/org/emmalanguage/api/package.scala

Given a `Meta.Tag[T] = runtime.universe.TypeTag[T]`, we can derive a `Meta[T]`.

[EXAMPLES] Workaround for implicit Meta parameters

---

NOTICE
emma-examples/emma-examples-flink/src/main/scala/org/emmalanguage/cli/FlinkExamplesRunner.scala
emma-examples/emma-examples-spark/src/main/scala/org/emmalanguage/cli/SparkExamplesRunner.scala
emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-language/pom.xml
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/ScalaSeq.scala
emma-language/src/main/scala/org/emmalanguage/io/csv/CSVColumn.scala
emma-language/src/main/scala/org/emmalanguage/io/csv/CSVConverter.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/Parquet.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetConverter.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetReadSupport.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetScalaSupport.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetWriteSupport.scala
emma-language/src/main/scala/org/emmalanguage/util/Iso.scala
emma-language/src/main/scala/org/emmalanguage/util/package.scala
emma-language/src/test/scala/org/emmalanguage/io/parquet/ParquetScalaSupportSpec.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala
pom.xml

[API] Type class based Parquet support

---

NOTICE
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetConverter.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetWriteSupport.scala
pom.xml

This adds the missing method symbols in `Common.API` and downgraded to Parquet 1.7.0 in order to make the library version compatible with what is bundled with Spark 2.0.1.

[API][IR] Parquet fixes

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-flink/src/main/scala/org/emmalanguage/api/converter/flink.scala
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/converter/CollConverter.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala
emma-spark/src/main/scala/org/emmalanguage/api/converter/spark.scala

Resolves #296.
Unfortunately I was not able to figure out a way to make all implicit instances available automatically with the
```scala
import org.emmalanguage.api._
```
import. For Spark-related conversions, one now has to additionally
```scala
import org.emmalanguage.api.conversions.spark._
```
and for Flink similarly
```scala
import org.emmalanguage.api.conversions.flink._
```

[API] Added conversion methods to backend-specific distributed collections.

---

emma-examples/emma-examples-flink/src/test/scala/org/emmalanguage/examples/ml/clustering/FlinkKMeansIntegrationSpec.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/examples/ml/clustering/BaseKMeansIntegrationSpec.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/TranslateToDataflows.scala

- It handles method parameters (former variables) as well;
- Distributed bag references are preserved when not in higher-order function;
- The transformations needs two passes instead of three.
Fixes #293

[IR] Fixed issues in automatic fetch insertion

---

emma-language/src/main/scala/org/emmalanguage/ast/Symbols.scala
emma-language/src/main/scala/org/emmalanguage/ast/Transversers.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/compiler/ir/DSCFAnnotations.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Combination.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Comprehension.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Normalize.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/ANF.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DCE.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DSCF.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala

Note that the first generator will never contain control flow, because it's not nested in a lambda. Subsequent generators, however, may contain control flow, since they are nested in `flatMap` calls.
This takes care of the problem only on comprehension level. `Core.flatten` will also require modification to work with nested `Let` blocks that contain control flow, but this is a separate issue.

[IR] Allowed control flow in generators and Combination

---

emma-language/src/main/scala/org/emmalanguage/ast/AST.scala
emma-language/src/main/scala/org/emmalanguage/test/TestMacros.scala
emma-language/src/test/scala/org/emmalanguage/compiler/RemoveShadowedThisSpec.scala
emma-spark/src/main/scala/org/emmalanguage/compiler/SparkMacro.scala

This is a somewhat hacky solution for #295 which removes the `this.*` qualifiers from the input tree.
This solves the issue with trees which do not produce valid code with `showCode` such as
```scala
class A {
val x = 42;
class A {
scala.Predef.println(A.this.x) // breaks here
}
}
```
The transformation is not sound and can break due to variable capture, e.g. if `x` were also defined in the inner `A` in the case above the semantics of the program will change after the transformation.
Fixes #295.

[IR] Added a post-pass to remove `this.*` qualifiers.

---

emma-examples/emma-examples-library/src/main/scala/org/emmalanguage/examples/ml/clustering/KMeans.scala
emma-language/src/main/scala/org/emmalanguage/api/package.scala

Also, removed `api.comparing` which was just a forwarder for `Ordering.fromLessThan`.
Closes #152

[TEST] Modified KMeans to use breeze.numerics.pow

---

NOTICE
emma-language/pom.xml
emma-language/src/main/scala/org/emmalanguage/compiler/lang/cf/CFG.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/cf/ControlFlow.scala
emma-language/src/main/scala/org/emmalanguage/compiler/tools/GraphTools.scala
emma-language/src/main/scala/org/emmalanguage/util/Monoids.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/cf/CFGSpec.scala
pom.xml

[quiver](https://github.com/Verizon/quiver) is a functional graph library for Scala (ported from Haskell). Before the graph contained only data-flow, now it is extended with control-flow (method calls). Nesting includes methods, comprehensions and lambdas (it's almost equivalent to the ownership relation).
- Data flows from RHS to LHS (and via `phi` nodes for method parameters);
- Lambda parameters currently contain no incoming `data` edges.
- Control flows from method caller to callee;
- Nesting flows from outer to inner.

[IR] Ported CFG to quiver and extended with control flow

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-flink/src/main/scala/org/emmalanguage/compiler/FlinkMacro.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/ir/Runtime.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/Caching.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/TranslateToDataflows.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/backend/CachingSpec.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala
emma-spark/src/main/scala/org/emmalanguage/compiler/SparkMacro.scala

Introduces
- a `ir.Runtime` module for runtime operators and an initial runtime
operator `cache`;
- a `backend.Caching` module with `addCacheCalls` transformation
that inserts `cache` calls when necessary.
Adds `Backend.cache` to the `emma.onFlink` and `emma.onSpark` pipelines.
The current implementation is a bit more conservative than what is possible, and (for example) will add `cache` calls to `xs` in the following:
```scala
val xs = DataBag(Seq(1,2,3,4,5))
if (z < 0) f(xs)
else g(xs)
```
A more elaborate version that considers cases such as the one above will be added after #300 is merged.

[IR] Added basic support for caching.

---

NOTICE
emma-examples/emma-examples-flink/pom.xml
emma-examples/emma-examples-flink/src/main/scala/org/emmalanguage/cli/FlinkExamplesRunner.scala
emma-examples/emma-examples-flink/src/test/scala/org/emmalanguage/examples/graphs/FlinkConnectedComponentsIntegrationSpec.scala
emma-examples/emma-examples-library/src/main/scala/org/emmalanguage/examples/graphs/ConnectedComponents.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/examples/graphs/BaseConnectedComponentsIntegrationSpec.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/examples/graphs/NaiveConnectedComponentsIntegrationSpec.scala
emma-examples/emma-examples-spark/src/main/scala/org/emmalanguage/cli/SparkExamplesRunner.scala
emma-examples/emma-examples-spark/src/test/scala/org/emmalanguage/examples/graphs/SparkConnectedComponentsIntegrationSpec.scala
emma-flink/pom.xml
emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-flink/src/main/scala/org/emmalanguage/api/FlinkMutableBag.scala
emma-flink/src/main/scala/org/emmalanguage/compiler/FlinkMacro.scala
emma-flink/src/test/scala/org/emmalanguage/compiler/flink/dataset/FlinkCodegenIntegrationSpec.scala
emma-language/src/main/scala/org/emmalanguage/api/Group.scala
emma-language/src/main/scala/org/emmalanguage/api/MutableBag.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Common.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/backend/Order.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DCE.scala
emma-language/src/test/scala/org/emmalanguage/compiler/BaseCodegenIntegrationSpec.scala
emma-spark/pom.xml
emma-spark/src/main/scala/org/emmalanguage/api/SparkMutableBag.scala
emma-spark/src/main/scala/org/emmalanguage/compiler/SparkMacro.scala
emma-spark/src/test/scala/org/emmalanguage/compiler/spark/rdd/SparkCodegenIntegrationSpec.scala
pom.xml
tools/license-mappings.xml

This is a somewhat simplified port of the `StatefulBag` abstraction from the old master branch.
The implementation is based on an abstract trait (`MutableBag`) with concrete implementations for Flink and Spark.
To validate that the current state works with a `ConnectedComponents` algorithm.
The main idea behind the port is that it will allow us to translate loop structures over a `MutableBag` instance to Flink's `iterateWithDelta` calls. I will propose backend-specific transformations for Flink's bulk- and delta-iterations in the next days.

Add `MutableBag` abstraction

---

NOTICE
emma-flink/src/test/scala/org/emmalanguage/api/FlinkDataSetSpec.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/MkParquetConverter.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetConverter.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetReadSupport.scala
emma-language/src/main/scala/org/emmalanguage/io/parquet/ParquetWriteSupport.scala
emma-language/src/main/scala/org/emmalanguage/util/Default.scala
emma-language/src/test/scala/org/emmalanguage/api/DataBagSpec.scala
emma-language/src/test/scala/org/emmalanguage/api/ScalaSeqSpec.scala
emma-spark/src/test/scala/org/emmalanguage/api/SparkDatasetSpec.scala
emma-spark/src/test/scala/org/emmalanguage/api/SparkRDDSpec.scala
pom.xml
scalastyle_config.xml

* Unified schemas with Spark (reverse engineered):
- `Option` and refence values treated as optional
- `Traversable` values with nested group structure
- `Byte`, `Short` and `Char` isomorphic to `Int`
* Added a `Default` type class for optional fields
* Added helper methods for writing a `message`, `group` or `field`
* Factored out derivation for case classes and reduced priority
* Increased max parameter number to 10 in `scalastyle_config`

[IO] Revisited ParquetConverter implementation

---

emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/compiler/integration/graphs/TransitiveClosureIntegrationSpec.scala
emma-language/src/main/scala/org/emmalanguage/ast/Terms.scala
emma-language/src/main/scala/org/emmalanguage/ast/Transversers.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/ANF.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DSCF.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/DSCFSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/TrampolineSpec.scala

* `ANF`:
- `var` definitions and assignments have only atoms on the RHS
- added `AsBlock` extractor for blocks replacing `decompose`
- added comments to clarify each case
- removed redundant helper methods
* `DSCF`:
- improved to one pass over AST (prev. two)
- `latest` environment contains one value per owner per `var` (prev. two)
- moved suffix definition before branches
- added comments to clarify each case
- adjusted `DSCFSpec` and `TrampolineSpec`
* `Core`: added `Comprehension` and `Continuation` matchers
* `Transversers`: empty trees in statement position are implicitly removed
* `TermName`, `TypeName`: improved fresh name generators

[IR] Simplified ANF and DSCF to match spec closer

---

emma-flink/src/main/scala/org/emmalanguage/compiler/FlinkMacro.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Comprehension.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Normalize.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/ANF.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/NormalizeSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/PrettyPrintSpec.scala
emma-spark/src/main/scala/org/emmalanguage/compiler/SparkMacro.scala

The refactoring allows to remove `[un]inlineLetExprs` altogether and `Core.dce` from some pipelines.

[IR] Refactored Normalize, PrettyPrintSpec, CombinationSpec

---

emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/compiler/integration/graphs/EnumerateTrianglesIntegrationSpec.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/compiler/integration/graphs/TransitiveClosureIntegrationSpec.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/compiler/integration/text/WordCountIntegrationSpec.scala
emma-language/src/main/scala/org/emmalanguage/ast/Symbols.scala
emma-language/src/main/scala/org/emmalanguage/ast/Terms.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/ReDeSugar.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/NormalizeSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/ReDeSugarSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/ANFSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/CSESpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/DCESpec.scala

Before:
```scala
val tuple = ("answer", 42)
val x$1: String = tuple._1
```
After:
```scala
val tuple = ("answer", 42)
val x$1: tuple._1.type = tuple._1
```
* Improves path-dependent type support (see `ANFSpec`)
* Sometimes avoids inaccessible type issues
* Fixed a bug in `Type.tree`
* Refactored `ReDeSugar`
* Adjusted specs where necessary

[IR] Precise types for symbols (no widen)

---

emma-language/src/main/scala/org/emmalanguage/ast/Symbols.scala
emma-language/src/main/scala/org/emmalanguage/ast/Transversers.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DSCF.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Trampoline.scala

Hook to bypass type-safety assertions: `Strategy.unsafe`.
Unsafe transformations are:
* `api.Tree.rename` - might change symbol infos
* `Core.trampoline` - wraps method return types in `TailRec`
* `DSCF.mapSuffix`  - when a different result type is specified

[IR] Ensure type-safe transformations (most cases)

---

emma-flink/src/main/scala/org/emmalanguage/api/FlinkDataSet.scala
emma-language/src/main/scala/org/emmalanguage/api/DataBag.scala
emma-language/src/main/scala/org/emmalanguage/api/ScalaSeq.scala
emma-language/src/main/scala/org/emmalanguage/api/alg/Alg.scala
emma-language/src/main/scala/org/emmalanguage/compiler/API.scala
emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/opt/FoldForestFusion.scala
emma-language/src/main/scala/org/emmalanguage/util/RanHash.scala
emma-language/src/test/scala/org/emmalanguage/api/DataBagSpec.scala
emma-language/src/test/scala/org/emmalanguage/api/ScalaSeqSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/opt/FoldForestFusionSpec.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkDataset.scala
emma-spark/src/main/scala/org/emmalanguage/api/SparkRDD.scala

Resolves #61 by adding a `DataBag.zipWithIndex` method.
In addition, reworked `DataBag.sample` as a reservoir sampling algorithm, which if not fully deterministic, at least makes it a bit more predictable. Subsequent calls of `xs.sample(k)` on the same object `xs` should return the same value in most situations.
As @fschueler proposed the addition in #61, I suggest he takes care of the review.

[API] Added `DataBag.zipWithIndex` and reworked `DataBag.sample`.

---

emma-language/src/main/scala/org/emmalanguage/ast/CommonAST.scala
emma-language/src/main/scala/org/emmalanguage/ast/Patterns.scala
emma-language/src/main/scala/org/emmalanguage/ast/Types.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/CoreValidate.scala
emma-language/src/test/scala/org/emmalanguage/api/DataBagSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/BaseCodegenIntegrationSpec.scala

* Enabled multi-way join test in `BaseCodegenIntegrationSpec`
* Narrowed valid top-level core trees to let blocks
* `DataBag.empty[Nothing]` works in `DataBagSpec`
* Added `PatExtr` constructor
* Added `VarArgType` and `ByNameType` constructors

[IR] Fixed a few TODOs

---

emma-examples/emma-examples-library/src/main/scala/org/emmalanguage/examples/imdb/GraphPreprocessing.scala
emma-examples/emma-examples-library/src/test/scala/org/emmalanguage/compiler/integration/imdb/GraphPreprocessingSpec.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/libsupport/LibSupport.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/ANFSpec.scala

This trivial case was not handled in the `inline` method, causing the error in #328.
Resolves #328.
However, the example in `GraphPreprocessingSpec` now fails to compile due to a different error:
```
An exception or error caused a run to abort: Type-checking error: reflective typecheck has failed: type mismatch;
found   : CreditType.Director.type
required: AnyRef
Note that Director extends Any, not AnyRef.
Such types can participate in value classes, but instances
cannot appear in singleton types or in reference comparisons. 
```
The problematic line is:
```
val Director$r1: CreditType.Director.type = CreditType.Director
```
it should be
```
val Director$r1 = CreditType.Director
```
because `CreditType.Director` inherits from `AnyRef` and not from `Any`.

[IR] Handle `CG.FunPar` in `LibSupport.inline`.

---

emma-flink/src/main/scala/org/emmalanguage/compiler/FlinkMacro.scala
emma-language/src/main/resources/reference.emma.conf
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Combination.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/Core.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/core/DSCF.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/core/DSCFSpec.scala
emma-spark/src/main/scala/org/emmalanguage/compiler/SparkMacro.scala

One can now choose between `dscfInv` and `trampoline` with the `emma.compiler.lower` parameter.
Resolves #280.

Added inverse DSCF transform

---

emma-language/src/main/scala/org/emmalanguage/compiler/Compiler.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/TreeNorm.scala
emma-language/src/main/scala/org/emmalanguage/compiler/lang/comprehension/Combination.scala
emma-language/src/test/scala/org/emmalanguage/compiler/lang/comprehension/CombinationSpec.scala

Solves #294 
A)
Added rules to transform guards for better join combination.
We partially use rules for normalization into conjunctive normal form.
1. Eliminate double negation (!!x => x);
2. Move negation inside disjunction (!(x || y) => !x && !y)
3. Split guards that return a conjunction in two guards. Repeat from 1. in sub-guards.
4. Collect all mutually independent guards of the form fi(x) == gi(y) with x and y fixed, and replace with ((f1(x), ... , fn(x)) == (g1(y), ... , gn(y)))
We don't use full CNF (see #294 ), because once a non-negated disjunction is involved, it cannot be processed any further. Thus [!(x && y) --> !x || !y] and demorgan [ (x || (y && z)) --> ((x || y) && (x || z)) ] are not useful for joins.
B)
Added a trait TreeNorm to be able to normalize let-blocks before …

[IR] Added guard transformations to improve join combination
